### ISSUE TITLE
redisio_configure fails during installation

### ISSUE THREAD

**Issue by kplimack** [brianbianco/redisio#252]
```
         * cookbook_file[/etc/pam.d/sudo] action create
           - update content in file /etc/pam.d/sudo from b473b9 to ae6ee3
           --- /etc/pam.d/sudo	2013-03-01 05:20:20.000000000 +0000
           +++ /etc/pam.d/.sudo20160122-2961-1v9y230	2016-01-22 20:20:53.649564311 +0000
           @@ -1,6 +1,10 @@
            #%PAM-1.0

           +auth       required   pam_env.so readenv=1 user_readenv=0
           +auth       required   pam_env.so readenv=1 envfile=/etc/default/locale user_readenv=0
           +session    required   pam_limits.so
            @include common-auth
            @include common-account
            @include common-session-noninteractive

       Recipe: redisio::configure
         * redisio_configure[redis-servers] action run[2016-01-22T20:20:53+00:00] WARN: Cloning resource attributes for file[] from prior resource (CHEF-3694)
       [2016-01-22T20:20:53+00:00] WARN: Previous file[]: /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:153:in `block (2 levels) in configure'
       [2016-01-22T20:20:53+00:00] WARN: Current  file[]: /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:160:in `block (2 levels) in configure'

           * user[redis] action create

             ================================================================================
             Error executing action `create` on resource 'user[redis]'
             ================================================================================

             NoMethodError
             -------------
             undefined method `[]' for nil:NilClass

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:103:in `block (4 levels) in configure'
             /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:89:in `block in configure'
             /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:38:in `each'
       /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:38:in `configure'


             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb

       96:       user current['user'] do
        97:         comment 'Redis service account'
       98:         supports :manage_home => true
       99:         home current['homedir']
             100:         shell current['shell']
             101:         system current['systemuser']
             102:         uid current['uid'] unless current['uid'].nil?
             103:         not_if { node['etc']['passwd']["#{current['user']}"] }
             104:       end
             105:       #Create the redis configuration directory

             Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:96:in `block (2 levels) in configure'

             user("redis") do
        action [:create]
        supports {:manage_home=>true}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        username "redis"
        comment "Redis service account"
        home "/var/lib/redis"
        shell "/bin/false"
        system true
        iterations 27855
        declared_type :user
        cookbook_name "redisio"
        not_if { #code block }
             end


           ================================================================================
           Error executing action `run` on resource 'redisio_configure[redis-servers]'
           ================================================================================

           NoMethodError
           -------------
           user[redis] (/tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb line 96) had an error: NoMethodError: undefined method `[]' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:103:in `block (4 levels) in configure'
           /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:89:in `block in configure'
           /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:38:in `each'
           /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:38:in `configure'
           /tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:22:in `block in class_from_file'

       Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/redisio/recipes/configure.rb

            30: redisio_configure "redis-servers" do
            31:   version redis['version'] if redis['version']
            32:   default_settings redis['default_settings']
            33:   servers redis_instances
            34:   base_piddir redis['base_piddir']
            35: end
            36:


           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/redisio/recipes/configure.rb:30:in `from_file'

           redisio_configure("redis-servers") do
             action :run
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :redisio_configure
             cookbook_name "redisio"
             recipe_name "configure"
             version "2.8.20"
             default_settings {"user"=>"redis", "group"=>"redis", "homedir"=>"/var/lib/redis", "shell"=>"/bin/false", "systemuser"=>true, "uid"=>nil, "ulimit"=>0, "configdir"=>"/etc/redis", "name"=>nil, "tcpbacklog"=>"511", "address"=>nil, "databases"=>"16", "backuptype"=>"rdb", "datadir"=>"/var/lib/redis", "unixsocket"=>nil, "unixsocketperm"=>nil, "timeout"=>"0", "keepalive"=>"0", "loglevel"=>"notice", "logfile"=>nil, "syslogenabled"=>"yes", "syslogfacility"=>"local0", "shutdown_save"=>false, "save"=>nil, "stopwritesonbgsaveerror"=>"yes", "rdbcompression"=>"yes", "rdbchecksum"=>"yes", "dbfilename"=>nil, "slaveof"=>nil, "masterauth"=>nil, "slaveservestaledata"=>"yes", "slavereadonly"=>"yes", "replpingslaveperiod"=>"10", "repltimeout"=>"60", "repldisabletcpnodelay"=>"no", "slavepriority"=>"100", "requirepass"=>nil, "rename_commands"=>nil, "maxclients"=>10000, "maxmemory"=>nil, "maxmemorypolicy"=>nil, "maxmemorysamples"=>nil, "appendfilename"=>nil, "appendfsync"=>"everysec", "noappendfsynconrewrite"=>"no", "aofrewritepercentage"=>"100", "aofrewriteminsize"=>"64mb", "luatimelimit"=>"5000", "slowloglogslowerthan"=>"10000", "slowlogmaxlen"=>"1024", "notifykeyspaceevents"=>"", "hashmaxziplistentries"=>"512", "hashmaxziplistvalue"=>"64", "listmaxziplistentries"=>"512", "listmaxziplistvalue"=>"64", "setmaxintsetentries"=>"512", "zsetmaxziplistentries"=>"128", "zsetmaxziplistvalue"=>"64", "hllsparsemaxbytes"=>"3000", "activerehasing"=>"yes", "clientoutputbufferlimit"=>[["normal", "0", "0", "0"], ["slave", "256mb", "64mb", "60"], ["pubsub", "32mb", "8mb", "60"]], "hz"=>"10", "aofrewriteincrementalfsync"=>"yes", "clusterenabled"=>"no", "clusterconfigfile"=>nil, "clusternodetimeout"=>5000, "includes"=>nil}
             servers [{"port"=>6379}]
             base_piddir "/var/run/redis"
           end

```

**Comment by kplimack** [comment]
its bailing on this `not_if { node['etc']['passwd']["#{current['user']}"] }`

**Comment by kplimack** [comment]
IMO, this not_if should be removed.  It is not the job of the redisio cookbook to make the user resource idempotent and it is causing errors.

**Comment by brianbianco** [comment]
That is probably true. This is probably from a recent merge. I'll review it and try to fix it. Is it possible you could try a SHA a couple commits earlier? It may solve your problem in the meantime.

**Comment by kplimack** [comment]
my problem was solved by simply removing the line containing the guard.

**Comment by brianbianco** [comment]
Thanks for updating with your fix.

**Comment by rtfee** [comment]
Hi, any idea on when this will be pushed to master? Thanks

**Comment by chewi** [comment]
I would not like this check removed but have fixed this in a different way. Please see #303.
